---  
- hosts: 172.31.44.126
  become: yes  
  tasks: 
  - name: executing linux commands 
    command: hostname -f 
    register: myresult 
  - name: i want to display result 
    debug:
      msg: "{{myresult}}"
  - name: install git 
    apt: 
      name: git 
      state: present 
    when: myresult."stderr"==" "
  - name: install apache2
    apt: 
      name: apache2
      state: present 
    when: myresult."stderr"!=" "