---  
- hosts: 172.31.44.126
  become: yes  
  tasks: 
  - name: install webserver
    apt: 
      name: apache22
      state: present
      ignor_errors: true
  - name: install wget 
    apt: 
      name: wget 
      state: present 
  - name: install git 
    apt: 
      name: git 
      state: present 