---  
- hosts: 172.31.44.126
  become: yes  
  tasks: 
  - include_tasks: myfile.yml
  - name: install webserver 
    apt: 
      name: apache2 
      state: present 
  - name: copy file from source to destination
    copy: 
      src: static.txt
      dest: /home/ubuntu/mystaticfile.txt