---  
- hosts: 172.31.44.126
  become: yes  
  tasks: 
  - include_tasks: myfile.yml
  - name: install webserver 
    apt: 
      name: apache2 
      state: present 
  - name: copy file from source to destination
    copy: 
      src: static.txt
      dest: /home/ubuntu/mystaticfile.txt
  - name: copying index.j2 file into ansible node side 
    template:
      src: myindex.j2
      dest: /var/www/html/index.html
  - name: download internet files 
    get_url:
      url: https://pkg.jenkins.io/debian/jenkins.io-2023.key
      dest: /home/ubuntu/jenkins.war
      force_basic_auth: yes

  handlers:
  - name: restartwebserver
    service:
      name: apache2
      state: restarted 
  
  - name: install git 
    apt:
      name: git 
      state: absent 
    notify: restartwebserver