---  
- hosts: 172.31.44.126
  become: yes  
  tasks: 
  - include_tasks: myfile.yml
  - name: install webserver 
    apt: 
      name: apache2 
      state: present 
  - name: copy file from source to destination
    copy: 
      src: static.txt
      dest: /home/ubuntu/mystaticfile.txt
  - name: copying index.j2 file into ansible node side 
    template:
      src: myindex.j2
      dest: /var/www/html/index.html
  - name: downloading internet files
    get_url:
      url: http://mirrors.jenkins.io/war-stable/latest/jenkins.war
      dest: /home/ubuntu/jenkins.war
    force_basic_auth: yes