---
- hosts: mywebservers
  become: yes 
  tasks:
  - name: install webserver
    apt:
      name: "{{webpackubuntu}}"
      state: present
    when: ansible_os_family=="Debian"
  - name: i want ot start webserver 
    service:
      name: "{{webpackubuntu}}"
      state: started
    when: ansible_os_family=="Debian"
  - name: install webserver
    yum: 
      name: "{{webpackredhat}}"
      state: latest
    when: ansible_os_family=="RedHat"
    
  - name: start apache2
    service:
      name: "{{webpackredhat}}"
      state: started
    when: ansible_os_family=="RedHat"