---
- hosts: all 
  become: yes 
  tasks:
  - name: install webserver
    apt:
      name: apache2
      state: present
    when: ansible_os_family=="Debian"
  - name: i want ot start webserver 
    service:
      name: apache2 
      state: started
    when: ansible_os_family=="Debian"
  - name: install webserver
    yum: 
      name: httpd 
      state: latest
    when: ansible_os_family=="RedHat"
    
  - name: start apache2
    service:
      name: httpd
      state: started
    when: ansible_os_family=="RedHat"